//! Mirror of `src/config/hook_config.rs`.
//!
//! Exercises the metadata generated by `register_hooks!`: per-direction
//! descriptions, shared-config support, and the `HookConfig` accessors.

use rcloud::{
    BackupHookConfig, BackupType, EncryptionHookConfig, HookConfig, HookExecType, Hooks,
    ZipHookConfig,
};

#[test]
fn describe_differs_per_direction() {
    assert_ne!(
        Hooks::Zip.describe(HookExecType::Push),
        Hooks::Zip.describe(HookExecType::Pull)
    );
}

#[test]
fn share_config_only_for_encryption() {
    assert!(Hooks::Encryption.share_config());
    assert!(!Hooks::Zip.share_config());
    assert!(!Hooks::Backup.share_config());
}

#[test]
fn modifies_filename_matches_registration() {
    let zip = HookConfig::Zip(ZipHookConfig {
        exec: HookExecType::Push,
        level: None,
        exclude: None,
    });
    let enc = HookConfig::Encryption(EncryptionHookConfig {
        exec: HookExecType::Push,
        hash: String::new(),
    });
    let backup = HookConfig::Backup(BackupHookConfig {
        exec: HookExecType::Push,
        types: vec![BackupType::Local],
        local_path: None,
        remote_path: None,
        replicas: 1,
    });

    assert!(zip.modifies_filename());
    assert!(enc.modifies_filename());
    assert!(!backup.modifies_filename());
}

#[test]
fn hook_type_and_exec_type_accessors() {
    let zip = HookConfig::Zip(ZipHookConfig {
        exec: HookExecType::Pull,
        level: None,
        exclude: None,
    });

    assert_eq!(zip.hook_type(), &Hooks::Zip);
    assert_eq!(zip.exec_type(), &HookExecType::Pull);
}

#[test]
fn hook_config_roundtrips_through_json() -> anyhow::Result<()> {
    let zip = HookConfig::Zip(ZipHookConfig {
        exec: HookExecType::Push,
        level: Some(9),
        exclude: Some(vec!["*.log".into()]),
    });

    let json = serde_json::to_string(&zip)?;
    let back: HookConfig = serde_json::from_str(&json)?;

    // Tagged enum survives the round-trip as the same variant/kind.
    assert_eq!(back.hook_type(), &Hooks::Zip);
    assert!(back.modifies_filename());
    Ok(())
}
